### ISSUE TITLE
About Jupyter Demo

### ISSUE THREAD

**Issue by XiwuChen** [wjy199708/Visualization_KITTI_Waymo#1]
Hi, 

I can NOT find the [notebook_demo.ipynb](https://github.com/wjy199708/Visualization_KITTI_Waymo/blob/master/notebook_demo.ipynb) as you mentioned at ./jupyter/README.md.
Can you upload this file?

Thanks for your great work.

**Comment by wjy199708** [comment]
@XiwuChen  Hi, The jupyter part of the demo gets stuck and the html page crashes during testing, so I didn't upload this part of the code. python command line code and the jupyter demo test code show the same content. I would recommend you to use python command line to visualize the data.

**Comment by XiwuChen** [comment]
Thanks for your reply. I found this file at https://github.com/kuixu/kitti_object_vis/blob/master/notebook_demo.ipynb. It works fine on my computer.
